"""
URL configuration for tutorial project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from tutorial.quickstart import views

router=routers.DefaultRouter() #Think of the DefaultRouter as an automatic URL factory.
"""
Instead of manually writing paths for GET /users/, POST /users/, GET /users/1/, etc.,
the router looks at your ViewSet and creates all those paths for you instantly.
"""
router.register(r"users", views.UserViewSet)
"""
The first argument (r"users") is the URL prefix.
This means any URL starting with /users/ will be handled by the UserViewSet.
"""
router.register(r"groups", views.GroupViewSet)

urlpatterns = [
    path("", include(router.urls)),#This takes all the URLs generated by the router 
                                   #(for users and groups) and plugs them into the root of your API.
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    #This adds the login/logout functionality to the DRF "Browsable API."
    path('admin/', admin.site.urls),
]
